apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  replicas: 5
  template:
    spec:
      containers:
      - image: schoolofdevops/vote:v3
        name: vote
        env:
          - name: OPTION_A
            valueFrom:
              configMapKeyRef:
                name: vote
                key: OPTION_A
          - name: OPTION_B
            valueFrom:
              configMapKeyRef:
                name: vote
                key: OPTION_B
